### ISSUE TITLE
The "url" argument must be of type string. Received undefined.

### ISSUE THREAD

**Issue by ShreyaNimma-at** [joshbirk/passport-forcedotcom#28]
We noticed the following error occur in this library, specifically at [this line of code](https://github.com/joshbirk/passport-forcedotcom/blob/master/lib/passport-forcedotcom/strategy.js#L100C24-L100C24). It's not clear to me under what circumstances `rawProfile.urls.users` is `undefined` but it's a fatal error. It is also hard to catch this error outside of this library because this line of code is within an asynchronous callback and handling errors within asynchronous callbacks is tricky in Node. It would be nice to handle this error in-place so that it doesn't terminate the calling process.

```
TypeError: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Url.parse (node:url:168:3)
    at Object.urlParse [as parse] (node:url:155:13)
    at node_modules/.store/passport-forcedotcom-npm-0.1.5-6bd2f32086/node_modules/passport-forcedotcom/lib/passport-forcedotcom/strategy.js:100:24
    at node_modules/.store/passport-forcedotcom-npm-0.1.5-6bd2f32086/node_modules/passport-forcedotcom/lib/passport-forcedotcom/strategy.js:133:5
    at passBackControl (node_modules/.store/oauth-npm-0.9.15-a6aae972bc/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (node_modules/.store/oauth-npm-0.9.15-a6aae972bc/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:552:15)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by trwinquist** [comment]
Running into this error as well, and would like to echo the sentiment that this error is really hard to catch and trap outside of the library because of the way its used. Would it be possible to do something like simply skip the photo url if the `rawProfile.urls.users` is undefined? something like [this]( https://github.com/joshbirk/passport-forcedotcom/blob/4ac5370639189a991952bae34d004ffee3d1ec90/lib/passport-forcedotcom/strategy.js#L96C4-L96C4).
Would be happy to open a PR for this to solve uncaught error.

**Comment by trwinquist** [comment]
@joshbirk let me know if the linked PR seems like an alright way to fix this!

**Comment by trwinquist** [comment]
@joshbirk could you publish the new version to npm so we can bump the version that we're using?

**Comment by kukidon-dev** [comment]
The same issue. @joshbirk please, publish the new version to the npm with mentioned fix. We would appreciate.

**Comment by trwinquist** [comment]
version 0.2.1 has been published

**Comment by kukidon-dev** [comment]
Thank you!

**Comment by trwinquist** [comment]
Just want to add a small note here about when this seemed to happen. It appears that free/demo salesforce accounts do not have this parameter available on the user profile while paid accounts do
