### ISSUE TITLE
meanjs.org / forcedotcom strategy

### ISSUE THREAD

**Issue by mrsollis** [joshbirk/passport-forcedotcom#9]
Thank you for this module... it seems to work perfectly.  I am struggling to connect it however with meanjs.org use of passport.  Hoping you could help.  I have this setup in the strategy folder:

```javascript
'use strict';

/**
 * Module dependencies.
 */

 var passport = require('passport'),
	url = require('url'),
	util = require('util'),
	ForceDotComStrategy = require('passport-forcedotcom').Strategy,
	config = require('../config'),
	users = require('../../app/controllers/users.server.controller');

module.exports = function() {
	// Use force.com strategy
	passport.use(new ForceDotComStrategy({
		clientID: config.forcedotcom.clientID,
		clientSecret: config.forcedotcom.clientSecret,
		callbackURL: config.forcedotcom.callbackURL,
		//passReqToCallback: true,
		scope: ['id','profile']
	}, 
	function(req, accessToken, refreshToken, profile, done) {
	//function verify(req, token, refreshToken, profile, done) {
			// Set the provider data and include tokens
			var providerData = profile;
			providerData.accessToken = refreshToken.access_token;
			providerData.id = profile._raw.user_id;
			
			// Create the user OAuth profile
			var providerUserProfile = {
				displayName: profile.displayName,
				email: profile.emails[0].value,
				username: profile._raw.nick_name,
				firstName: profile._raw.first_name,
				lastName: profile._raw.last_name,
				provider: 'forcedotcom',
				providerIdentifierField: 'user_id',
				providerData: providerData,
				
			};
			
			// Save the user OAuth profile
			users.saveOAuthUserProfile(req, providerUserProfile, done);
			
			return done(null, profile);
		}
	));
};
```

I have this used for routes:

```javascript
app.route('/auth/forcedotcom').get(passport.authenticate('forcedotcom'));
app.route('/auth/forcedotcom/callback').get(users.oauthCallback('forcedotcom'));
```

my config looks like this:

```javascript
'use strict';

module.exports = {
	db: 'mongodb://localhost/dops-labs-dev',
	app: {
		title: 'DOps Labs - Development Environment'
	},
	facebook: {
		clientID: process.env.FACEBOOK_ID || 'CLIENT_ID',
		clientSecret: process.env.FACEBOOK_SECRET || 'CLIENT_SECRET',
		callbackURL: '/auth/facebook/callback'
	},
	twitter: {
		clientID: process.env.TWITTER_KEY || 'CONSUMER_KEY',
		clientSecret: process.env.TWITTER_SECRET || 'CONSUMER_SECRET',
		callbackURL: '/auth/twitter/callback'
	},
	google: {
		clientID: process.env.GOOGLE_ID || 'APP_ID',
		clientSecret: process.env.GOOGLE_SECRET || 'APP_SECRET',
		callbackURL: '/auth/google/callback'
	},
	linkedin: {
		clientID: process.env.LINKEDIN_ID || 'APP_ID',
		clientSecret: process.env.LINKEDIN_SECRET || 'APP_SECRET',
		callbackURL: '/auth/linkedin/callback'
	},
	github: {
		clientID: process.env.GITHUB_ID || 'APP_ID',
		clientSecret: process.env.GITHUB_SECRET || 'APP_SECRET',
		callbackURL: '/auth/github/callback'
	},
	forcedotcom: {
		clientID: process.env.FORCEDOTDOM_ID || 'CLIENT_ID',
		clientSecret: process.env.FORCEDOTCOM_SECRET || 'CLIENT_SECRET',
		callbackURL: '/auth/forcedotcom/callback'
	},
	mailer: {
		from: process.env.MAILER_FROM || 'MAILER_FROM',
		options: {
			service: process.env.MAILER_SERVICE_PROVIDER || 'MAILER_SERVICE_PROVIDER',
			auth: {
				user: process.env.MAILER_EMAIL_ID || 'MAILER_EMAIL_ID',
				pass: process.env.MAILER_PASSWORD || 'MAILER_PASSWORD'
			}
		}
	}
};
```

the console looks like this I am receiving is:
```
GET /auth/forcedotcom/callback?code=ACCESSTOKEN_WAS_HERE 302 1352.329 ms - 58
CastError: Cast to ObjectId failed for value "SFDC_USER_ID_WAS_HERE" at path "_id"
    at ObjectId.cast (/Users/userXYZ/Sites/labs/node_modules/mongoose/lib/schema/objectid.js:117:13)
    at ObjectId.castForQuery (/Users/userXYZ/Sites/labs/node_modules/mongoose/lib/schema/objectid.js:167:17)
    at Query.cast (/Users/userXYZ/Sites/labs/node_modules/mongoose/lib/query.js:2355:32)
    at Query.findOne (/Users/userXYZ/Sites/labs/node_modules/mongoose/lib/query.js:1125:10)
    at Function.findOne (/Users/userXYZ/Sites/labs/node_modules/mongoose/lib/model.js:1064:13)
    at /Users/userXYZ/Sites/labs/config/passport.js:22:8
    at pass (/Users/userXYZ/Sites/labs/node_modules/passport/lib/authenticator.js:353:9)
    at Authenticator.deserializeUser (/Users/userXYZ/Sites/labs/node_modules/passport/lib/authenticator.js:358:5)
    at SessionStrategy.authenticate (/Users/userXYZ/Sites/labs/node_modules/passport/lib/strategies/session.js:49:28)
    at attempt (/Users/userXYZ/Sites/labs/node_modules/passport/lib/middleware/authenticate.js:341:16)
/Users/userXYZ/Sites/labs/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Users/userXYZ/Sites/labs/node_modules/express/lib/response.js:666:10)
    at ServerResponse.res.location (/Users/userXYZ/Sites/labs/node_modules/express/lib/response.js:780:8)
    at ServerResponse.redirect (/Users/userXYZ/Sites/labs/node_modules/express/lib/response.js:819:8)
    at /Users/userXYZ/Sites/labs/app/controllers/users/users.authentication.server.controller.js:91:17
    at /Users/userXYZ/Sites/labs/node_modules/passport-linkedin/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:44:48
    at pass (/Users/userXYZ/Sites/labs/node_modules/passport/lib/authenticator.js:293:14)
    at Authenticator.serializeUser (/Users/userXYZ/Sites/labs/node_modules/passport/lib/authenticator.js:295:5)
    at IncomingMessage.req.login.req.logIn (/Users/userXYZ/Sites/labs/node_modules/passport-linkedin/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:43:29)
    at /Users/userXYZ/Sites/labs/app/controllers/users/users.authentication.server.controller.js:89:8
```

**Comment by joshbirk** [comment]
*Can't set headers after they are sent.* makes me very suspicious that it isn't down to a single passport module, especially since linked-in seems to jump in there as well.  Is mean possibly sending multiple responses?
